In [1]:
import numpy as np
a = np.array([[1, 3, 2], [4,5,3]])
b = np.array([[2, 1, 4], [9, 5, 2]])
a + b


array([[ 3,  4,  6],
       [13, 10,  5]])

In [ ]:
import numpy as np
a = np.array([[1, 3, 2], [4,5,3]])
b = np.array([[2, 1, 4], [9, 5, 2]])
a - b

array([[ 3,  4,  6],
       [13, 10,  5]])

In [ ]:
import numpy as np
a = np.array([[1, 3, 2], [4,5,3]])
b = np.array([[2, 1, 4], [9, 5, 2]])
a * b

array([[ 2,  3,  8],
       [36, 25,  6]])

In [ ]:
import numpy as np
a = np.array([[1, 3, 2], [4,5,3]])
b = np.array([[2, 1, 4], [9, 5, 2]])
a / b

array([[0.5       , 3.        , 0.5       ],
       [0.44444444, 1.        , 1.5       ]])

In [ ]:
import numpy as np
a = np.array([[1, 3, 2], [4,5,3]])
b = np.array([[2, 1, 4], [9, 5, 2]])
a % b

array([[1, 0, 2],
       [4, 0, 1]])